#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jun 11 22:32:01 2017

@author: sauravpradhan19
"""
import numpy 
x=int(input("Enter number x:"))
y=int(input("Enter number y:"))
print("X**y = ",x**y)
print("log(x) = ",int(numpy.log2(x)))